#!/bin/bash
dpkg-deb -bZgzip projects/com.rgx.colorpods debs
dpkg-deb -bZgzip projects/com.rgx.lvstatic debs
dpkg-deb -bZgzip projects/com.rgx.minecraftpods debs
dpkg-deb -bZgzip projects/com.rgx.digital debs
dpkg-deb -bZgzip projects/com.rgx.ghostpods debs
dpkg-deb -bZgzip projects/com.rgx.rosegold debs
dpkg-deb -bZgzip projects/com.rgx.purplepods debs
dpkg-deb -bZgzip projects/com.rgx.anapods debs
dpkg-deb -bZgzip projects/com.rgx.twig debs
dpkg-deb -bZgzip projects/com.rgx.3dbundleid debs
dpkg-deb -bZgzip projects/com.rgx.sbew98bundle debs
dpkg-deb -bZgzip projects/com.rgx.propods debs
dpkg-deb -bZgzip projects/com.rgx.sound debs
dpkg-deb -bZgzip projects/com.rgx.lighttube debs
dpkg-deb -bZgzip projects/com.rgx.13bundleid debs
dpkg-deb -bZgzip projects/com.rgx.theme debs
dpkg-deb -bZgzip projects/com.rgx.juulpods13 debs
dpkg-deb -bZgzip projects/com.rgx.86 debs
dpkg-deb -bZgzip projects/com.rgx.lbppods debs
dpkg-deb -bZgzip projects/com.rgx.persona5 debs
dpkg-deb -bZgzip projects/com.rgx.warioland debs
dpkg-deb -bZgzip projects/com.rgx.delta debs
dpkg-deb -bZgzip projects/com.rgx.sizetest debs
